In [1]:
import numpy as np

Understanding the norm of a matrix


The norm of a matrix is a way to measure the "size" or "magnitude" of a matrix, similar to how the absolute value measures the size of a number. It's a non-negative real number that satisfies certain properties.

There are different types of matrix norms, each with its own meaning and applications. Some common ones include:

**Frobenius norm:** This norm calculates the square root of the sum of the squares of all the elements in the matrix. It's often used to measure the overall size or magnitude of a matrix, similar to the Euclidean norm for vectors.

**1-norm:** This norm calculates the maximum absolute column sum of the matrix. It represents the maximum influence a single column can have on the output.

**Infinite-norm:**This norm calculates the maximum absolute row sum of the matrix. It represents the maximum influence a single row can have on the output.






**Matrix norms have various applications in linear algebra and numerical analysis, such as:**

**Error analysis:** Norms can be used to measure the error between two matrices or vectors.

**Stability analysis:** Norms can be used to analyze the stability of numerical algorithms.

**Conditioning of matrices:** Norms can be used to measure how sensitive a matrix is to changes in its elements.

### Matrix Norms

$$ \lVert M \rVert_{p} = \Big( \sum_{i=1}^n \sum_{j=1}^m \mid a_{ij} \mid^{p} \Big)^{1/p}$$

Fornenium norm (Eucledian norm) of $M_{n \times m}$:

$$ \lVert M \rVert = \Big( \sum_{i=1}^n \sum_{j=1}^m \mid a_{ij} \mid^{2} \Big)^{1/2}$$

1-norm:

$$ \lVert M \rVert_{1} = \max\limits_{1\le j \le m} \sum_{i=1}^n \mid a_{ij} \mid $$

infinite-norm:

$$ \lVert M \rVert_{\infty} = \max\limits_{1\le i \le n} \sum_{j=1}^m \mid a_{ij} \mid $$

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
B = np.linalg.norm(A, ord = 1)
C = np.linalg.norm(A, ord= 2)
D = np.linalg.norm(A, ord= 'fro')
print(B)
print(C)
print(D)

18.0
16.84810335261421
16.881943016134134


Underdstanding the difference between dot and matmul


Matrix multiplication is an operation that takes two matrices as input and produces a new matrix as output. It's a fundamental operation in linear algebra with various applications in mathematics, computer science, and engineering.

Here are some key points about matrix multiplication:

Conditions for multiplication: Two matrices can be multiplied only if the number of columns in the first matrix is equal to the number of rows in the second matrix. Otherwise, the multiplication is undefined.
Resulting matrix: The resulting matrix has the same number of rows as the first matrix and the same number of columns as the second matrix.
Calculation: The elements of the resulting matrix are calculated by taking the dot product of the corresponding row of the first matrix and the corresponding column of the second matrix.
Non-commutative: Matrix multiplication is not commutative, meaning that the order of multiplication matters. In general, AB is not equal to BA.
Associative: Matrix multiplication is associative, meaning that (AB)C = A(BC).

Talking about horizontal and vertical stack


In [35]:
I = np.array([[1,2], [3,4]])
O = np.array([5,6])
L = np.vstack((I, O))
print(L)
Q = np.array([[2, 1], [7, 8]])
N = np.hstack((Q, I))
print(N)

[[1 2]
 [3 4]
 [5 6]]
[[2 1 1 2]
 [7 8 3 4]]


In [13]:
##Algorithm to multiply m times of row j to row i
def add_row(m, A, i, j):
  #m is the multiplier
  n = A.shape[0]
  E = np.eye(n)
  if i == j:
    E[i,j] = m +1
  else:
    E[i, j] = m
  return E @ A

In [16]:
print(A)
A_added = add_row(2, A, 0, 1)
print(A_added)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 9. 12. 15.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [18]:
##Algorithm to swap rows in a matrix
def swap_row(A, i, j):
  n = A.shape[0]
  E = np.eye(n)
  E[i,i] = 0
  E[j,j] = 0
  E[i,j] = 1
  E[j,i] = 1
  return E @ A

In [20]:
##Algorith to scale a row of a matric my some factor
def scale_row(m , A, i):
  #m is the factors to scale with
  n = A.shape[0]
  E = np.eye(n)
  E[i,i] = m
  return E @ A