<a href="https://colab.research.google.com/github/Rushikesh-Chavan-777/Computational-Methods-In-Material-Science/blob/main/SolveLinearEq_DirectMethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <font color="blue"> Practice Notebook: Solve for the Set of Linear Equations using Direct Methods</font>

In [ ]:
import numpy as np

In [ ]:
### Simpler functions (Row operations)

In [ ]:
def add_row(A,m,i,j):

    '''
    m: multiplier
    Add m times row j to row i in a matrix A
    '''
    # n stores the the size of a matrix A of size n x n
    n = A.shape[0] # row dimension of A
    E = np.eye(n) # nxn identity matrix
    if i==j:
        E[i,j] = m + 1
    else:
        E[i,j] = m
    return E @ A

In [ ]:
def scale_row(A,s,i):
    '''
    A: a matrix
    s: scale factor
    Multiply row i of A by scale factor s
    '''
    n = A.shape[0]
    E = np.eye(n)
# [i,i] is the index of diagonal element of row i that is scaled by s
    E[i,i] = s
    return E @ A

In [ ]:
def swap_rows(A,i,j):
    '''
    Interchange rows i and j of a matrix A
    Note the identity matrix E is always a square matrix
    Swap rows of identity matrix E to interchange rows of A
    Returns E @ A
    '''
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

#### <font color="blue">Steps (or algorithm) for Gaussian elimination with pivoting</font>

#### #Solving  using Gaussian elimination with partial pivoting

Input: A: n x n matrix, b: vector of n dimensions

Output: x: vector of n dimensions

Afull = stack(A,b) # A is now n x n+1, as we append b as a new column

#### #Start the loop

for k=1:n do # traverse through columns of A

#### #Find pivot (largest element of active column)

pivot = Afull[k][k] #Intitialize Afull[1][1] as starting value

pivot_row = k

for i=k+1:n do

if Afull[i][k] > pivot:

pivot = Afull[i][k]

pivot_row = k
#### #Swap k-th row with row with the pivot element

swap(Afull,k,pivot_row) # Afull[k][k] is now the pivot

#### #Update bottom-right part of matrix

for i=k+1:n:

m = A[i][k]/A[k][k]

for j=1:n+1 do:

Afull[i][j] = Afull[i][j] - m*Afull[k][j]
#### #After this, A should be in upper diagonal form.

#### #Solving for x:

x[n] = Afull[n][n+1]/Afull[n][n]

for i=n-1:1 do:

sum = 0

for j=i+1:n do:

sum = sum + Afull[i][j]*x[j]

x[i] = (Afull[i][n+1] - sum ) / Afull[i][i]

#### # x now contains the solution of the system

In [ ]:
### Example
A = np.array([[4.0, -2.0, 1.0], [-3.0, -1.0, 4.0], [1.0, -1.0, 3.0]])
print('A=',A)
B = np.array([[15.0], [8.0], [13.0]])
print('B=',B)

n = len(A)
print('n=',n)

#Pivoting --> swap --> eliminaton

for k in range(n-1):
    maxindex = abs(A[k:,k]).argmax() + k
#    print(maxindex)
    #swap
    if maxindex != k:
        A[[k, maxindex]] = A[[maxindex,k]]
        B[[k, maxindex]] = B[[maxindex,k]]
#    print(A)
#    print(B)
    #Eliminate
    for row in range(k+1, n):
        multiplier = A[row,k]/A[k,k]
        print(multiplier)
        A[row, k:] = A[row,k:] - multiplier*A[k,k:]
        print('A[row]', A[row,k:])
        B[row] = B[row] - multiplier*B[k]
        print('B[row]', B[row])
#    print(A)
#    print(B)

A= [[ 4. -2.  1.]
 [-3. -1.  4.]
 [ 1. -1.  3.]]
B= [[15.]
 [ 8.]
 [13.]]
n= 3
-0.75
A[row] [ 0.   -2.5   4.75]
B[row] [19.25]
0.25
A[row] [ 0.   -0.5   2.75]
B[row] [9.25]
0.2
A[row] [0.  1.8]
B[row] [5.4]


In [ ]:
print(A)
print(B)

[[ 4.   -2.    1.  ]
 [ 0.   -2.5   4.75]
 [ 0.    0.    1.8 ]]
[[15.  ]
 [19.25]
 [ 5.4 ]]


In [ ]:
x = np.zeros(n)
x

array([0., 0., 0.])

In [ ]:
#Backsubstitution:

#for k in range(n-1, -1, -1):
#    print(k)
#    print(A[k, k+1:n])
#    print(x[k+1:n])
#    x[k] = (B[k] - np.dot(A[k, k+1:n], x[k+1:n]))/A[k,k]
#    print(x[k])

In [ ]:
#print(f'roots={x}')

### Finding inverse of a matrix using Gauss-Jordan method

In [ ]:
Y = np.array([[5,4,2],[-1,2,1],[1,1,1]])
print(Y)

[[ 5  4  2]
 [-1  2  1]
 [ 1  1  1]]


In [ ]:
#np.round?

In [ ]:
#Augmented matrix A formed by horizontally stacking Y with an identity matrix of same shape
A=np.hstack([Y,np.eye(Y.shape[0])])
print(A)

[[ 5.  4.  2.  1.  0.  0.]
 [-1.  2.  1.  0.  1.  0.]
 [ 1.  1.  1.  0.  0.  1.]]


In [ ]:
A1 = swap_rows(A,0,2)
print(A1)

[[ 1.  1.  1.  0.  0.  1.]
 [-1.  2.  1.  0.  1.  0.]
 [ 5.  4.  2.  1.  0.  0.]]


In [ ]:
A2 = add_row(A1,1,1,0)
print(A2)

[[1. 1. 1. 0. 0. 1.]
 [0. 3. 2. 0. 1. 1.]
 [5. 4. 2. 1. 0. 0.]]


In [ ]:
A3 = add_row(A2,-5,2,0)
print(A3)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  3.  2.  0.  1.  1.]
 [ 0. -1. -3.  1.  0. -5.]]


In [ ]:
A4 = swap_rows(A3,1,2)
print(A4)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0. -1. -3.  1.  0. -5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [ ]:
A5 = scale_row(A4,-1,1)
print(A5)

[[ 1.  1.  1.  0.  0.  1.]
 [ 0.  1.  3. -1.  0.  5.]
 [ 0.  3.  2.  0.  1.  1.]]


In [ ]:
A6 = add_row(A5,-3,2,1)
print(A6)

[[  1.   1.   1.   0.   0.   1.]
 [  0.   1.   3.  -1.   0.   5.]
 [  0.   0.  -7.   3.   1. -14.]]


In [ ]:
A7 = scale_row(A6,-1/7,2)
print(A7)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          3.         -1.          0.          5.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [ ]:
A8 = add_row(A7,-3,1,2)
print(A8)

[[ 1.          1.          1.          0.          0.          1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [ ]:
A9 = add_row(A8,-1,0,2)
print(A9)

[[ 1.          1.          0.          0.42857143  0.14285714 -1.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [ ]:
A10 = add_row(A9,-1,0,1)
print(A10)

[[ 1.          0.          0.          0.14285714 -0.28571429  0.        ]
 [ 0.          1.          0.          0.28571429  0.42857143 -1.        ]
 [ 0.          0.          1.         -0.42857143 -0.14285714  2.        ]]


In [ ]:
Yinv = A10[:,3:]
print(Yinv)

[[ 0.14285714 -0.28571429  0.        ]
 [ 0.28571429  0.42857143 -1.        ]
 [-0.42857143 -0.14285714  2.        ]]


In [ ]:
A10[:,3:]

array([[ 0.14285714, -0.28571429,  0.        ],
       [ 0.28571429,  0.42857143, -1.        ],
       [-0.42857143, -0.14285714,  2.        ]])

In [ ]:
np.linalg.inv(Y)

array([[ 0.14285714, -0.28571429,  0.        ],
       [ 0.28571429,  0.42857143, -1.        ],
       [-0.42857143, -0.14285714,  2.        ]])

In [ ]:
import numpy as np

def GEPP(A, b, doPivot = True):
    '''
    Gaussian elimination with partial pivoting.

    input: A is an n x n numpy matrix
           b is an n x 1 numpy array
    output: x is the solution of Ax=b
            with the entries permuted in
            accordance with the pivoting
            done by the algorithm
    post-condition: A and b have been modified.
    '''
    n = len(A)
    print(f'n={n}')
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between"+
                         "A and b.", b.size, n)
    # k represents the current pivot row. Since GE traverses the matrix in the
    # upper right triangle, we also use k for indicating the k-th diagonal
    # column index.

    # Elimination
    for k in range(n-1):
        if doPivot:
            # Pivot
            maxindex = abs(A[k:,k]).argmax() + k
            if A[maxindex, k] == 0:
                raise ValueError("Matrix is singular.")
            # Swap
            if maxindex != k:
                A[[k,maxindex]] = A[[maxindex, k]]
                b[[k,maxindex]] = b[[maxindex, k]]
        else:
            if A[k, k] == 0:
                raise ValueError("Pivot element is zero. Try setting doPivot to True.")
        #Eliminate
        for row in range(k+1, n):
            multiplier = A[row,k]/A[k,k]
            A[row, k:] = A[row, k:] - multiplier*A[k, k:]
            b[row] = b[row] - multiplier*b[k]
    # Back Substitution
    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        print(f'k={k}')
        x[k] = (b[k] - np.dot(A[k,k+1:n],x[k+1:n]))/A[k,k]
    return x

# <font face="Sans" color="blue"> LU Factorization</font>

We aim to decompose a matrix $A$ into $L$ and $U$, which represent _lower_ and _upper triangular matrix_ respectively. And $L$ must have $1$'s on its principal diagonal.
$$
A = LU
$$
For instance,
$$
A=\underbrace{\left[\begin{array}{cccc}
1 & 0 & 0 & 0 \\
* & 1 & 0 & 0 \\
* & * & 1 & 0 \\
* & * & * & 1
\end{array}\right]}_{L}\underbrace{\left[\begin{array}{cccc}
* & * & * & * \\
0 & * & * & * \\
0 & 0 & * & * \\
0 & 0 & 0 & *
\end{array}\right]}_{U}
$$

An example here:

$$
A =
\begin{bmatrix}
9 & 3 & 6\\3 & 4 & 6\\0 & 8 & 8\\
\end{bmatrix}
$$
Use Gaussian elimination to get U. Store the multipliers. They are elements of L

In [ ]:
import scipy as sp

In [ ]:
A = np.array([[9, 3, 6], [3, 4, 6], [0, 8, 8]]); A

array([[9, 3, 6],
       [3, 4, 6],
       [0, 8, 8]])

In [ ]:
P, L, U = sp.linalg.lu(A)
print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.375      1.        ]]
[[9. 3. 6.]
 [0. 8. 8.]
 [0. 0. 1.]]


In [ ]:
P@L@U #returns A

array([[9., 3., 6.],
       [3., 4., 6.],
       [0., 8., 8.]])

Note that the SciPy ```lu``` function gives us $L$, $U$ and $P$.

$P$ which is a **permutation matrix**. In general we may not need row swaps to convert $A$ into $U$. In some cases we need to switch/swap the rows, otherwise decomposition will not happen.

Thus Scipy uses $PLU$ decomposition to make the procedure always possible
$$
A  = PLU
$$

Solve the linear system：
$$
\begin{align}
3x_1-7x_2 -2x_3+2x_4&=-9\\
-3x_1+5x_2 +x_3 &=5\\
6x_1-4x_2 -5x_4&=7\\
-9x_1+5x_2 -5x_3+12x_4&=11\\
\end{align}
$$
In matrix form:
$$
\underbrace{\left[\begin{array}{rrrr}
3 & -7 & -2 & 2 \\
-3 & 5 & 1 & 0 \\
6 & -4 & 0 & -5 \\
-9 & 5 & -5 & 12
\end{array}\right]}_{A}
\left[\begin{array}{r}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{array}\right]
=
\underbrace{\left[\begin{array}{r}
-9 \\
5 \\
7 \\
11
\end{array}\right]}_{b}
$$
Perform $LU$ decomposition:

$$\underbrace{\left[\begin{array}{rrrr}
3 & -7 & -2 & 2 \\
-3 & 5 & 1 & 0 \\
6 & -4 & 0 & -5 \\
-9 & 5 & -5 & 12
\end{array}\right]}_{A}
=\underbrace{
\left[\begin{array}{rrrr}
1 & 0 & 0 & 0 \\
-1 & 1 & 0 & 0 \\
2 & -5 & 1 & 0 \\
-3 & 8 & 3 & 1
\end{array}\right]}_{L}\underbrace{\left[\begin{array}{rrrr}
3 & -7 & -2 & 2 \\
0 & -2 & -1 & 2 \\
0 & 0 & -1 & 1 \\
0 & 0 & 0 & -1
\end{array}\right]}_{U}$$

Replace $A$ by $LU$, we get $L(Ux) = b$, now solve this pair of equations

$$
Ly = b\\
Ux = y
$$

Construct augmented matrix $[L|b]$

$$
\underbrace{
\left[\begin{array}{rrrr}
1 & 0 & 0 & 0 \\
-1 & 1 & 0 & 0 \\
2 & -5 & 1 & 0 \\
-3 & 8 & 3 & 1
\end{array}\right]}_{L}
\underbrace{\left[\begin{array}{r}
y_1 \\
y_2 \\
y_3 \\
y_4
\end{array}\right]}_{y}
=
\underbrace{\left[\begin{array}{r}
-9 \\
5 \\
7 \\
11
\end{array}\right]}_{b}
$$

$$
\left[\begin{array}{r}
y_1 \\
y_2 \\
y_3 \\
y_4
\end{array}\right]=
\left[\begin{array}{r}
-9 \\
-4 \\
5 \\
1
\end{array}\right]
$$

Next we solve $Ux = y$ to get solution

In [ ]:
AA = np.array([[1,2,-1,-1],[4,8,-4,2],[1,1,1,2],[3,3,4,4]])
b = np.array([[-9,5,7,11]])
print(AA)
print(b)

[[ 1  2 -1 -1]
 [ 4  8 -4  2]
 [ 1  1  1  2]
 [ 3  3  4  4]]
[[-9  5  7 11]]


In [ ]:
P,L,U = sp.linalg.lu(AA)
#print(P)
#print(L)
#print(U)
L1 = P@L
#print(L1)
y = sp.linalg.solve(L1,b.T)
#print(y)
x = sp.linalg.solve(U,y)
print(x)

sol=sp.linalg.solve(AA,b.T)
sol

[[-22.16666667]
 [ 11.83333333]
 [  3.66666667]
 [  6.83333333]]


array([[-22.16666667],
       [ 11.83333333],
       [  3.66666667],
       [  6.83333333]])

In [ ]:
def lu(A):

    #Get the number of rows
    n = A.shape[0]

    U = A.copy()
    L = np.eye(n, dtype=np.double)
#    L = np.eye(n, dtype=float)

    #Loop over rows
    for i in range(n):

        #Eliminate entries below i with row operations
        #on U and reverse the row operations to
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] = U[i+1:] - factor[:, np.newaxis] * U[i]

    return L, U

In [ ]:
AA

array([[ 1,  2, -1, -1],
       [ 4,  8, -4,  2],
       [ 1,  1,  1,  2],
       [ 3,  3,  4,  4]])

In [ ]:
#lu(AA)